In [1]:
import numpy as np

In [2]:
np.arange(19)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18])

In [17]:
a=np.array([1,2,3,4,4])
b=np.arange(10)
c=b.reshape(5,2)
print(b,c)
print("c sum",c.sum(axis=0))
print("a sum",a.sum(axis=0))

[0 1 2 3 4 5 6 7 8 9] [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
c sum [20 25]
a sum 14


In [23]:
c.shape
c.dtype
c.ndim
c.T
c.itemsize

8

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])
print(arr[1,2]) # o which row, 1 which element index
print(arr[0:2, 1:4])

8
[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
a=np.array([1,2,3,4])
a=np.arange(4)
x=[True,False,False,True]
print(a[x])

[0 3]
